# Generated by Django 5.1.1 on 2024-10-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_college_delete_colleges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='course_offered',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='college',
            name='email',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='college',
            name='location',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='college',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='college',
            name='university',
            field=models.CharField(max_length=300),
        ),
    ]
