# Generated by Django 5.1.1 on 2024-10-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_college_course_offered_alter_college_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='course_offered',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='college',
            name='email',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='college',
            name='location',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='college',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='college',
            name='ownership_type',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='college',
            name='phone_number',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='college',
            name='university',
            field=models.CharField(max_length=500),
        ),
    ]
